services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - DB_USER=udin
      - DB_PASSWORD=udin
      - DB_NAME=udin_db
      - DB_HOST=db
      - DB_PORT=5432


  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=udin
      - POSTGRES_PASSWORD=udin
      - POSTGRES_DB=udin_db

volumes:
  postgres_data: