services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    environment:
      - DB_USER=udin
      - DB_PASSWORD=udin
      - DB_NAME=udin_db
      - DB_HOST=db
      - DB_PORT=5432


  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=udin
      - POSTGRES_PASSWORD=udin
      - POSTGRES_DB=udin_db
  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning

volumes:
  postgres_data:
  redis_data: